<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '79507200b41a0280a35ff41a38f5159c',
  'DATABASE_URL' => 'mysql://symfony:symfony@mysql:3306/symfony',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
);